MVC Project/LibraryMSMVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LibraryMSMVC.Models;
using System.Web.Mvc;

namespace LibraryMSMVC.Controllers
{
    public class AdminController : Controller
    {
        private AdminEntity adminDb = new AdminEntity();

        // Returns admin login view, here admin can login.
        [HttpGet]
        [HandleError]
        public ActionResult Login()
        {
            return View();
        }

        // Checks admin credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        [HandleError]
        public ActionResult Login(tblAdmin admin)
        {
            var adm = adminDb.tblAdmins.SingleOrDefault(a => a.AdminEmail == admin.AdminEmail && a.AdminPass == admin.AdminPass);
            if (adm != null)
            {
                int id = adm.AdminId;
                Session["adminId"] = adm.AdminId;
                return RedirectToAction("Index","TblBooks", new { id = id });
            }
            else if (admin.AdminEmail == null && admin.AdminPass == null)
            {
                return View();
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }
        /* Admin credentials validation two
        public ActionResult Validate(tblAdmin admin)
        {
            var adm = db.tblAdmins.SingleOrDefault(a => a.AdminEmail == admin.AdminEmail && a.AdminPass == admin.AdminPass);
            if (adm != null)
            {
                int id = adm.AdminId;
                return RedirectToAction("Index", "tblBooks", new { @id = id });
            }
            else if (admin.AdminEmail == null && admin.AdminPass == null)
            {
                return View("Login");
            }
            ViewBag.Message = "User name and password are not matching";
            return View("Login");
        }*/

        // Admin logout, redirect to main. 
        [HandleError]
        public ActionResult Logout()
        {
            Session.Remove("adminId");
            return RedirectToAction("Home", "Main");
        }
    }
}

MVC Project/LibraryMSMVC/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryMSMVC.Controllers
{
    public class MainController : Controller
    {
        // Returns home view.
        public ActionResult Home()
        {
            return View();
        }

        // Returns about view.
        public ActionResult About()
        {
            return View();
        }

        // Returns contact view.
        public ActionResult Contact()
        {
            return View();
        }

        // Returns login view.
        public ActionResult Login()
        {
            return View();
        }
    }
}

MVC Project/LibraryMSMVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryMSMVC.Models;

namespace LibraryMSMVC.Controllers
{
    public class UserController : Controller
    {
        UserEntity userDb = new UserEntity();

        // Returns user login view, here admin can login.
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // Checks user credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        public ActionResult Login(tblUser user)
        {
            var adm = userDb.tblUsers.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserId;
                Session["userName"] = adm.UserName;
                return RedirectToAction("Index", "Borrow", new { userId = adm.UserId, userName = adm.UserName });
            }
            else if (user.UserEmail == null && user.UserPass == null)
            {
                return View();
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }

        /* User credentials validation two
        public ActionResult Validate(tblUser user)
        {
            var adm = db.tblUsers.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserId;
                Session["userName"] = adm.UserName;
                ViewBag.userId= adm.UserId;
                ViewBag.userId = adm.UserId;
                return RedirectToAction("Index", "Borrow", new { userId = adm.UserId, userName = adm.UserName });
            }
               else if (user.UserEmail == null && user.UserPass == null)
            {
                return View("Login");
            }
            ViewBag.Message = "User name and password are not matching";
            return View("Login");
        }
        */

        // User logout, redirect to main. 
        public ActionResult Logout()
        {
            Session.Remove("userId");
            Session.Remove("userName");
            return RedirectToAction("Home", "Main");
        }
    }
}

MVC Project/LibraryMSMVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UrLMS</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#5cb85c;">
            <div style="background-color:#d9534f; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("UrLMS", "Index", "tblBooks", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "AdminHome", "AdminTransaction", new { area = "" }, new { @class = "nav-link" , style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "AdminAbout", "AdminTransaction", new { area = "" }, new { @class = "nav-link" , style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "AdminContact", "AdminTransaction", new { area = "" }, new { @class = "nav-link" , style = "display:inline" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Books", "Index", "TblBooks", new { area = "" }, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Users", "Index", "TblUsers", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px">
                        @Html.ActionLink("Request", "Requests", "AdminTransaction", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Accepted", "Accepted", "AdminTransaction", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Return", "Return", "AdminTransaction", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                </ul>
                <span class="text-light" style="padding-top:1px; padding-right:15px">Welcome back Admin!!</span>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item btn btn-sm btn-success">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "Admin", null, new { @class = "nav-link", onclick = "return alert('Logged out successfully');" , style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>
        
        <footer>
            <div style="" class="card text-center text-white bg-success">
                <div class="card-header">
                    Thank you for your work
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - UrLMS</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#5cb85c;">
        <div style="background-color:#d9534f; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MVC Project/LibraryMSMVC/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UrLMS</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#d9534f;">
            <div style="background-color:#292b2c; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("UrLMS", "Home", "Main", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "Home", "Main", new { @class = "nav-link icon", style="display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "About", "Main", new { @class = "nav-link icon", style="display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "Contact", "Main", new { @class = "nav-link icon", style="display:inline" })
                    </li>
                </ul>

                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-sign-in-alt"></i>
                        @Html.ActionLink("Login", "Login", "Main", new { @class = "nav-link icon", style="display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
       
    </div>
    <div style="padding-left:20px; padding-right:20px;">
        @RenderBody()
    </div>
    <div>
        <footer>
            <div style="" class="card text-center text-white bg-dark">
                <div class="card-header">
                    Thank you for visiting us
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - UrLMS</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#d9534f;">
        <div style="background-color:#292b2c; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVC Project/LibraryMSMVC/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UrLMS</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#d9534f;">
            <div style="background-color:#5cb85c; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("UrLMS", "MenuBorrow", "Borrow", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "UserHome", "Borrow",null, new { @class = "nav-link icon",style="display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "UserAbout", "Borrow",null,  new { @class = "nav-link icon" ,style="display:inline"  })
                    </li>
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "UserContact", "Borrow",null, new { @class = "nav-link icon" ,style="display:inline"  })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Borrow", "MenuBorrow", "Borrow", new { area = "" }, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Requested", "MenuRequested", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li style="padding-left: 5px; padding-right: 5px ">
                        @Html.ActionLink("Received", "MenuReceived", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                        
                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Rejected", "MenuRejected", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                        
                    </li>
                </ul>
                <span class="text-light" style="padding-top:1px; padding-right:15px">Welcome back @Session["userName"]!!</span>
                <ul class="navbar-nav justify-content-end">

                    <li class="nav-item btn btn-sm btn-danger">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "User", null, new { @class = "nav-link", onclick = "return alert('Logged out successfully');", style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>
        
        <footer>
            <div style="" class="card text-center text-white bg-danger">
                <div class="card-header">
                    Thank you for visiting us
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - UrLMS</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#d9534f;">
        <div style="background-color:#5cb85c; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>