MVC Project/LibraryMSMVC/Models/tblUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        public int UserId { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "The Name field must be between 4 and 30 character")]
        [RegularExpression("(-?([A-Z].\\s)?([A-Z][a-z]+)\\s?)+([A-Z]'([A-Z][a-z]+))?", ErrorMessage = "The Name field is invalid")]
        [DisplayName("Name")]
        public string UserName { get; set; }
        [Required]
        [DisplayName("Gender")]
        public string UserGender { get; set; }
        [Required]
        [DisplayName("Department")]
        public string UserDep { get; set; }
        [Required]
        [DisplayName("Admission Number")]
        public Nullable<int> UserAdmNo { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email Address")]
        public string UserEmail { get; set; }
        [Required]
        [StringLength(15, MinimumLength = 8, ErrorMessage = "The Password field must be atleast 8 character long")]
        [DisplayName("Password")]
        public string UserPass { get; set; }
    }
}

MVC Project/LibraryMSMVC/Controllers/TblUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMSMVC.Models;

namespace LibraryMSMVC.Controllers
{
    public class TblUsersController : Controller
    {
        private UserEntity userDb = new UserEntity();

        // GET: tblUsers
        public ActionResult Index()
        {
            return View(userDb.tblUsers.ToList());
        }

        // GET: tblUsers Json
        public ActionResult GetAll()
        {
            var userlist = userDb.tblUsers.ToList();
            return Json(new { data = userlist }, JsonRequestBehavior.AllowGet);
        }

        // GET: tblUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = userDb.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // GET: tblUsers/Create
        public ActionResult Create()
        {  
            return View();
        }

        // POST: tblUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,UserGender,UserDep,UserAdmNo,UserEmail,UserPass")] tblUser tblUser)
        {
            Session.Remove("emailExists");
            if (ModelState.IsValid)
            {
                
                if (userDb.tblUsers.Where(u=>u.UserEmail==tblUser.UserEmail).Count()>0)
                {
                    Session["emailExists"] = "The Email address is already exists.";
                    return View(tblUser);
                }
                else
                {
                    Session["operationMsg"] = "User added successfully";
                    userDb.tblUsers.Add(tblUser);
                    userDb.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(tblUser);
        }

        // Remove the session datas which are used for alerts
        // OperationAlert
        public ActionResult OperationAlert()
        {
            Session.Remove("operationMsg");
            return RedirectToAction("Index");
        }

        // GET: tblUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = userDb.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: tblUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,UserGender,UserDep,UserAdmNo,UserEmail,UserPass")] tblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                Session["operationMsg"] = "User updated successfully";
                userDb.Entry(tblUser).State = EntityState.Modified;
                userDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblUser);
        }

        // GET: tblUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = userDb.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: tblUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblUser tblUser = userDb.tblUsers.Find(id);
            userDb.tblUsers.Remove(tblUser);
            userDb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                userDb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC Project/LibraryMSMVC/Views/tblUsers/Create.cshtml
@model LibraryMSMVC.Models.tblUser

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Add user</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="col-6 offset-3 card">
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-row form-group">
        <div class="col">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", placeholder = "Soubhagya P" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>

        <div class="col">
            @Html.LabelFor(model => model.UserGender, htmlAttributes: new { @class = "control-label" })
            <br />
            <div class="col-11 card card-body ">
                @{
                    List<String> genderlist = new List<string>() { "Male", "Female", "Other", };
                    foreach (var gender in genderlist)
                    {
                        <div>
                            @Html.RadioButtonFor(model => model.UserGender, gender, new { htmlAttributes = new { @class = "form-control" } })

                            <span class="text-muted" style="padding-left:5px; padding-right:5px;">@gender</span>
                        </div>
                    }
                }
            </div>
            @Html.ValidationMessageFor(model => model.UserGender, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            @Html.LabelFor(model => model.UserDep, htmlAttributes: new { @class = "control-label" })

            @Html.DropDownListFor(model => model.UserDep, new List<SelectListItem> {
            new SelectListItem{ Text="Ec", Value="Ec"},
            new SelectListItem{ Text="Cs", Value="Cs"},
            new SelectListItem{ Text="Mech", Value="Mech"},
            new SelectListItem{ Text="Civil", Value="Civil"},
            new SelectListItem{ Text="Bio", Value="Bio"},
            new SelectListItem{ Text="It", Value="It"},
           }, "Select department", new { @class = "form-control" })
            
            @Html.ValidationMessageFor(model => model.UserDep, "", new { @class = "text-danger" })

        </div>

        <div class="col">
            @Html.LabelFor(model => model.UserAdmNo, htmlAttributes: new { @class = "control-label" })
            
                @Html.EditorFor(model => model.UserAdmNo, new { htmlAttributes = new { @class = "form-control", placeholder = "2015360" } })
                @Html.ValidationMessageFor(model => model.UserAdmNo, "", new { @class = "text-danger" })
          
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label" })
            
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control", placeholder = "sou@gmail.com" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
                <p class="text-danger">@Session["emailExists"]</p>
           
        </div>

        <div class="col">
            @Html.LabelFor(model => model.UserPass, htmlAttributes: new { @class = "control-label" })
            
                @Html.EditorFor(model => model.UserPass, new { htmlAttributes = new { @class = "form-control", placeholder = "123123pwd" } })
                @Html.ValidationMessageFor(model => model.UserPass, "", new { @class = "text-danger" })
           
        </div>
    </div>
    <div class="form-group">
        <button onclick="" type="submit" value="Submit" class="btn btn-sm btn-primary" data-toggle='tooltip' title='Submit user'>
            <i class="fas fa-check-circle"></i>
            Submit
        </button>
    </div>
    

</div>
}
<br />

<div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to user list'>
    <i class="fas fa-long-arrow-alt-left"></i>
    @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>
<br />
<br />

MVC Project/LibraryMSMVC/Views/tblUsers/Delete.cshtml
@model LibraryMSMVC.Models.tblUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h4>Are you sure you want to delete this?</h4>
<hr />
<div>
    

    <div class="col-6 offset-3 card">

        <br />
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserName)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserName)
                    </p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserGender)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserGender)
                    </p>
                </div>
            </div>
        </div>
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserDep)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserDep)
                    </p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserAdmNo)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserAdmNo)
                    </p>
                </div>
            </div>
        </div>
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserEmail)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserEmail, new { style = "" })
                    </p>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserPass)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserPass)
                    </p>
                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div type="submit" value="Delete" class="">
                    <button onclick="deleteMessage()" class="btn btn-sm btn-danger" data-toggle='tooltip' title='Delete user'>
                        <i class="fas fa-trash iconop"></i>
                        Delete
                    </button>
                </div>
            </div>
        }
    </div>
</div>
<br />

<div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to user list'>
    <i class="fas fa-long-arrow-alt-left"></i>
    @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>
<br />
<br />

@section scripts{
    <script>
        @*Scripts for delete alert*@
        function deleteMessage() {
            alert("User deleted successfully")
        }
    </script>
}

MVC Project/LibraryMSMVC/Views/tblUsers/Details.cshtml
@model LibraryMSMVC.Models.tblUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>User details</h4>
<hr />
<div>

    <div class="col-6 offset-3 card">

        <br />
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserName)
                    </h5>
                    <p class="text-muted">
                    @Html.DisplayFor(model => model.UserName)
                    </p>
                        </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserGender)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserGender)
                    </p>
                        </div>
            </div>
        </div>
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserDep)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserDep)
                    </p>
                        </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserAdmNo)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserAdmNo)
                    </p>
                        </div>
            </div>
        </div>
        <div class="form-row form-group text-center">
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserEmail)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserEmail, new { style=""})
                    </p>
                        </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5>
                        @Html.DisplayNameFor(model => model.UserPass)
                    </h5>
                    <p class="text-muted">
                        @Html.DisplayFor(model => model.UserPass)
                    </p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-sm btn-dark" data-toggle='tooltip' title='Edit user'>
                <i class="fas fa-edit"></i>
                @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }, new { @class = "", style = "text-decoration:none; color: white" })
            </button>
        </div>
    </div>
</div>
    <br />
    <div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to user list'>
        <i class="fas fa-long-arrow-alt-left"></i>
        @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
    </div>
    <br />
    <br />

MVC Project/LibraryMSMVC/Views/tblUsers/Edit.cshtml
@model LibraryMSMVC.Models.tblUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Update user</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-6 offset-3 card">
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)
        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })

            </div>
            <div class="col">
                @Html.LabelFor(model => model.UserGender, htmlAttributes: new { @class = "control-label" })

                <br />
                <div class="col-11 card card-body ">
                    @{
                        List<String> genderlist = new List<string>() { "Male", "Female", "Other", };
                        foreach (var gender in genderlist)
                        {
                            <div>
                                @Html.RadioButtonFor(model => model.UserGender, gender, new { htmlAttributes = new { @class = "form-control" } })

                                <span class="text-muted" style="padding-left:5px; padding-right:5px;">@gender</span>
                            </div>
                        }
                    }
                </div>                
                @Html.ValidationMessageFor(model => model.UserGender, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">

            <div class="col">
                @Html.LabelFor(model => model.UserDep, htmlAttributes: new { @class = "control-label" })

                @Html.DropDownListFor(model => model.UserDep, new List<SelectListItem> {
                new SelectListItem{ Text="Ec", Value="Ec"},
                new SelectListItem{ Text="Cs", Value="Cs"},
                new SelectListItem{ Text="Mech", Value="Mech"},
                new SelectListItem{ Text="Civil", Value="Civil"},
                new SelectListItem{ Text="Bio", Value="Bio"},
                new SelectListItem{ Text="It", Value="It"},
                }, "Select department", new { @class = "form-control" })


                @Html.ValidationMessageFor(model => model.UserDep, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.UserAdmNo, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.UserAdmNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserAdmNo, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">

            <div class="col">
                @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label" })
                <input type="text" value="@Model.UserEmail " class = "form-control" disabled="disabled"/>
                @Html.HiddenFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })


            </div>

            <div class="col">
                @Html.LabelFor(model => model.UserPass, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.UserPass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPass, "", new { @class = "text-danger" })

            </div>
        </div>


        <div class="form-group">
            <button onclick="" type="submit" value="Submit" class="btn btn-sm btn-primary" data-toggle='tooltip' title='Update user'>
                <i class="fas fa-check-circle"></i>
                Update
            </button>
        </div>
    </div>
}

<br />
<div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to user list'>
    <i class="fas fa-long-arrow-alt-left"></i>
    @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>
<br />
<br />

MVC Project/LibraryMSMVC/Views/tblUsers/Index.cshtml
@model IEnumerable<LibraryMSMVC.Models.tblUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<h2>Index</h2>*@
<br />
<h4>User list</h4>
<hr />
<div class="btn btn-sm btn-primary" data-toggle='tooltip' title='Add user'>
    <i class="far fa-plus-square"></i>
    @Html.ActionLink("Add", "Create", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>
<br />
<br />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserDep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserAdmNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserPass)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                UserName
            </th>
            <th>
                UserGender
            </th>
            <th>
                UserDep
            </th>
            <th>
                UserAdmNo
            </th>
            <th>
                UserEmail
            </th>
            <th>
                UserPass
            </th>

        </tr>
    </tbody>
</table>
<br />

@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        @*Data table plugin*@
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/tblUsers/GetAll",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "UserName" },
                    { "data": "UserGender" },
                    { "data": "UserDep" },
                    { "data": "UserAdmNo" },
                    { "data": "UserEmail" },
                    { "data": "UserPass" },
                    {
                        "data": "UserId", "render": function (idhere) {

                            return " <a class='btn btn-sm btn-dark text-light' data-toggle='tooltip' title='Edit user' href='@Url.Action("Edit", "TblUsers")/" + idhere + "'> <i class='fas fa-edit'></i> Edit</a> <a class='btn btn-sm btn-warning text-light', style='margin-left:px' data-toggle='tooltip' title='User details' href='@Url.Action("Details", "TblUsers")/" + idhere+"' > <i class='fas fa-info-circle iconop'></i> Details</a > <a class='btn btn-sm btn-danger text-light', style='margin-left:px' data-toggle='tooltip' title='Delete user' href='@Url.Action("Delete", "TblUsers")/" + idhere+"' > <i class='fas fa-trash iconop'></i> Delete</a > ";
                        },
                        "orderable": false,
                        "width": "225px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Add new items"
                }
            });
        });
    </script>
}


@if (Session["operationMsg"] != null)
{
    <script type="text/javascript">
            @*Popups the alert if the session data is there*@
            window.onload = function () {
                alert("@Session["operationMsg"]");
                window.location.href = "/TblUsers/OperationAlert";
            };
    </script>

}












@*<div class="card">
        <table class="table-sm">
            <tr class="bg-success text-light">
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserGender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserDep)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserAdmNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserEmail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserPass)
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserGender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserDep)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserAdmNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserPass)
                    </td>
                    <td>
                        <div class="btn btn-group-sm">
                            <div class="btn btn-dark btn-sm iconop">
                                <i class="fas fa-edit"></i>
                                @Html.ActionLink("Edit", "Edit", null, new { id = item.UserId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                            <div class="btn btn-sm btn-warning">
                                <i class="fas fa-info-circle iconop"></i>
                                @Html.ActionLink("Details", "Details", null, new { id = item.UserId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                            <div class="btn btn-sm btn-danger">
                                <i class="fas fa-trash iconop"></i>
                                @Html.ActionLink("Delete", "Delete", null, new { id = item.UserId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>*@