MVC Project/LibraryMSMVC/Models/tblBook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMSMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBook
    {
        public int BookId { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "The Title field must be between 4 and 30 character")]
        [RegularExpression("^([A-Z][a-z]+([ ]?[a-z]?['-]?[A-Z][a-z]+)*)$", ErrorMessage ="The Title field is invalid")]
        [DisplayName("Title")]
        public string BookTitle { get; set; }
        
        [Required]
        [DisplayName("Category")]
        public string BookCategory { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "The Author field must be between 4 and 30 character")]
        [RegularExpression("^([A-Z][a-z]+([ ]?[a-z]?['-]?[A-Z][a-z]+)*)$", ErrorMessage = "The Author field is invalid")]
        [DisplayName("Author")]
        public string BookAuthor { get; set; }
        
        [Required]
        [DisplayName("Copies")]
        public Nullable<int> BookCopies { get; set; }

        [DisplayName("Publication")]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "The Publication field must be between 4 and 30 character")]
        [RegularExpression("^([A-Z][a-z]+([ ]?[a-z]?['-]?[A-Z][a-z]+)*)$", ErrorMessage = "The Publication field is invalid")]
        public string BookPub { get; set; }
        
        [DisplayName("Pub Name")]
        [StringLength(30, MinimumLength = 4, ErrorMessage = "The Pub Name field must be between 4 and 30 character")]
        [RegularExpression("^([A-Z][a-z]+([ ]?[a-z]?['-]?[A-Z][a-z]+)*)$", ErrorMessage = "The Pub Name field is invalid")]
        public string BookPubName { get; set; }
        
        [Required]
        [RegularExpression("((?:[\\dX]{13})|(?:[\\d\\-X]{17})|(?:[\\dX]{10})|(?:[\\d\\-X]{13}))", ErrorMessage = "The ISBN field is invalid")]
        [DisplayName("ISBN")]
        public string BookISBN { get; set; }

        [Range(1700,2020)]
        [DisplayName("Copyright")]
        public Nullable<int> Copyright { get; set; }
        
        [Required]
        [DisplayName("Date Added")]
        public string DateAdded { get; set; }
        
        [Required]
        [DisplayName("Status")]
        public string Status { get; set; }
    }
}

MVC Project/LibraryMSMVC/Controllers/TblBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMSMVC.Models;

namespace LibraryMSMVC.Controllers
{
    public class TblBooksController : Controller
    {
        private BookEntity bookDb = new BookEntity();

        // GET: tblBooks
        public ActionResult Index()
        {
            return View(bookDb.tblBooks.ToList());
        }
        // GET: tblBooks Json
        public ActionResult GetAll()
        {
            var booklist = bookDb.tblBooks.ToList();
            return Json(new { data = booklist }, JsonRequestBehavior.AllowGet);
        }

        // GET: tblBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBook tblBook = bookDb.tblBooks.Find(id);
            if (tblBook == null)
            {
                return HttpNotFound();
            }
            return View(tblBook);
        }

        // GET: tblBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblBooks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookId,BookTitle,BookCategory,BookAuthor,BookCopies,BookPub,BookPubName,BookISBN,Copyright,DateAdded,Status")] tblBook tblBook)
        {
            if (ModelState.IsValid)
            {
                Session["operationMsg"] = "Book added successfully";
                bookDb.tblBooks.Add(tblBook);
                bookDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblBook);
        }

        // Remove the session datas which are used for alerts
        // OperationAlert
        public ActionResult OperationAlert()
        {
            Session.Remove("operationMsg");
            return RedirectToAction("Index");

        }

        // GET: tblBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBook tblBook = bookDb.tblBooks.Find(id);
            if (tblBook == null)
            {
                return HttpNotFound();
            }
            return View(tblBook);
        }

        // POST: tblBooks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookId,BookTitle,BookCategory,BookAuthor,BookCopies,BookPub,BookPubName,BookISBN,Copyright,DateAdded,Status")] tblBook tblBook)
        {
            if (ModelState.IsValid)
            {
                Session["operationMsg"] = "Book updated successfully";
                bookDb.Entry(tblBook).State = EntityState.Modified;
                bookDb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblBook);
        }

        // GET: tblBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblBook tblBook = bookDb.tblBooks.Find(id);
            if (tblBook == null)
            {
                return HttpNotFound();
            }
            return View(tblBook);
        }

        // POST: tblBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblBook tblBook = bookDb.tblBooks.Find(id);
            bookDb.tblBooks.Remove(tblBook);
            bookDb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                bookDb.Dispose();
            }
            base.Dispose(disposing);
        }
        

    }
}

MVC Project/LibraryMSMVC/Views/tblBooks/Create.cshtml
@model LibraryMSMVC.Models.tblBook

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h4>Add book</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-6 offset-3 card">
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control ", placeholder = "Catch Me If You Can" } })
                @Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.BookCategory, htmlAttributes: new { @class = "control-label" })

                @Html.DropDownListFor(model => model.BookCategory, new List<SelectListItem> {
                new SelectListItem{ Text="Action", Value="Action"},
                new SelectListItem{ Text="Drama", Value="Drama"},
                new SelectListItem{ Text="Romance", Value="Romance"},
                new SelectListItem{ Text="Fiction", Value="Fiction"},
                new SelectListItem{ Text="Science", Value="Science"},
                new SelectListItem{ Text="Horror", Value="Horror"},
               }, "Select catagory", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookCategory, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.BookAuthor, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookAuthor, new { htmlAttributes = new { @class = "form-control", placeholder = "Frank Abagnale Jr" } })
                @Html.ValidationMessageFor(model => model.BookAuthor, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.BookCopies, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookCopies, new { htmlAttributes = new { @class = "form-control", placeholder = "15" } })
                @Html.ValidationMessageFor(model => model.BookCopies, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.BookPub, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookPub, new { htmlAttributes = new { @class = "form-control", placeholder = "Grosset & Dunlap" } })
                @Html.ValidationMessageFor(model => model.BookPub, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.BookPubName, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookPubName, new { htmlAttributes = new { @class = "form-control", placeholder = "Hunted Forger" } })
                @Html.ValidationMessageFor(model => model.BookPubName, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.BookISBN, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.BookISBN, new { htmlAttributes = new { @class = "form-control", placeholder = "0-448-16538-4" } })
                @Html.ValidationMessageFor(model => model.BookISBN, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.Copyright, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.Copyright, new { htmlAttributes = new { @class = "form-control", placeholder = "1980" } })
                @Html.ValidationMessageFor(model => model.Copyright, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-row form-group">
            <div class="col">
                @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control datepicker", placeholder = "05/23/1983" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })

            </div>

            <div class="col">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label" })

                @Html.DropDownListFor(model => model.Status, new List<SelectListItem> {
                new SelectListItem{ Text="New", Value="New"},
                new SelectListItem{ Text="Old", Value="Old"},
                new SelectListItem{ Text="Damaged", Value="Damaged"}
                }, "Select status", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            <button onclick="" type="submit" value="Submit" class="btn btn-sm btn-primary" data-toggle='tooltip' title='Submit book'>
                <i class="fas fa-check-circle"></i>
                Submit
            </button>
        </div>

    </div>
    <br />
}

<div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to book list'>
    <i class="fas fa-long-arrow-alt-left"></i>
    @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>
<br />
<br />

@*External scripts for date picker plugins*@
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        @*Date picker plugin*@
        $(function () {
            $(".datepicker").datepicker({ changeMonth: true, changeYear: true });
        });

    </script>
}

MVC Project/LibraryMSMVC/Views/tblBooks/Delete.cshtml
@model LibraryMSMVC.Models.tblBook

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Are you sure you want to delete this?</h4>
<hr />

<div>

    <div>

        <div class="col-6 offset-3 card">
            <br />
            <div class="form-row form-group text-center">
                <div class="col">
                    <div class="card">
                        <h5>@Html.DisplayNameFor(model => model.BookTitle)</h5>
                        <p class="text-muted">@Html.DisplayFor(model => model.BookTitle)</p>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <h5>@Html.DisplayNameFor(model => model.BookCategory)</h5>
                        <p class="text-muted"> @Html.DisplayFor(model => model.BookCategory)</p>
                    </div>
                </div>
            </div>
            <div class="form-row form-group text-center">
                <div class="col">
                    <div class="card">
                        <h5> @Html.DisplayNameFor(model => model.BookAuthor)</h5>
                        <p class="text-muted"> @Html.DisplayFor(model => model.BookAuthor)</p>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <h5>@Html.DisplayNameFor(model => model.BookCopies)</h5>
                        <p class="text-muted">@Html.DisplayFor(model => model.BookCopies)</p>
                    </div>
                </div>
            </div>

            <div class="form-row form-group text-center">
                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.BookPub)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.BookPub)
                        </p>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.BookPubName)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.BookPubName)
                        </p>
                    </div>
                </div>
            </div>
            <div class="form-row form-group text-center">
                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.BookISBN)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.BookISBN)
                        </p>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.Copyright)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.Copyright)
                        </p>
                    </div>
                </div>
            </div>

            <div class="form-row form-group text-center">
                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.DateAdded)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.DateAdded)
                        </p>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <h5>
                            @Html.DisplayNameFor(model => model.Status)
                        </h5>
                        <p class="text-muted">
                            @Html.DisplayFor(model => model.Status)
                        </p>
                    </div>
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div type="submit" value="Delete" class="">
                        <button onclick="deleteMessage()" class="btn btn-sm btn-danger" data-toggle='tooltip' title='Delete book'>
                            <i class="fas fa-trash iconop"></i>
                            Delete
                        </button>
                    </div>
                </div>
            }
        </div>
    </div>

    <br />
    <div class="btn btn-sm btn-secondary" data-toggle='tooltip' title='Back to book list'>
        <i class="fas fa-long-arrow-alt-left"></i>
        @Html.ActionLink("Back", "Index", null, new { @class = "", style = "text-decoration:none; color: white" })
    </div>
    <br />
    <br />
</div>

@section scripts{
    <script>
        @*Scripts for delete alert*@
        function deleteMessage(){
            alert("Book deleted successfully")
        }
    </script>
}

MVC Project/LibraryMSMVC/Views/tblBooks/Index.cshtml
@model IEnumerable<LibraryMSMVC.Models.tblBook>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Book list</h4>
<hr />
<div class="btn btn-sm btn-primary" data-toggle='tooltip' title='Add book'>
    <i class="far fa-plus-square"></i>
    @Html.ActionLink("Add", "Create", null, new { @class = "", style = "text-decoration:none; color: white" })
</div>

<br />
<br />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table-sm table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookAuthor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookCopies)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookPub)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookPubName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Copyright)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookCategory
            </th>
            <th>
                BookAuthor
            </th>
            <th>
                BookCopies
            </th>
            <th>
                BookPub
            </th>
            <th>
                BookPubName
            </th>
            <th>
                BookISBN
            </th>
            <th>
                Copyright
            </th>
            <th>
                DateAdded
            </th>
            <th>
                Status
            </th>

        </tr>
    </tbody>
</table>
<br />

@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/tblBooks/GetAll",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookCategory" },
                    { "data": "BookAuthor" },
                    { "data": "BookCopies" },
                    { "data": "BookPub" },
                    { "data": "BookPubName" },
                    { "data": "BookISBN" },
                    { "data": "Copyright" },
                    { "data": "DateAdded" },
                    { "data": "Status" },
                    {
                        "data": "BookId", "render": function (idhere) {

                            return " <a class='btn btn-sm btn-dark text-light' data-toggle='tooltip' title='Edit book' href='@Url.Action("Edit", "TblBooks")/" + idhere + "'> <i class='fas fa-edit'></i> Edit</a> <a class='btn btn-sm btn-warning text-light', style='margin-left:px' data-toggle='tooltip' title='Book details' href='@Url.Action("Details", "TblBooks")/" + idhere+"' > <i class='fas fa-info-circle iconop'></i> Details</a > <a class='btn btn-sm btn-danger text-light', style='margin-left:px' data-toggle='tooltip' title='Delete book' href='@Url.Action("Delete", "TblBooks")/" + idhere+"' > <i class='fas fa-trash iconop'></i> Delete</a > ";
                        },
                        "orderable": false,
                        "width": "245px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Add new items"
                }
            });
        });
    </script>
}

@if (Session["operationMsg"] != null)
{
    <script type="text/javascript">
            @*Popups the alert if the session data is there*@
            window.onload = function () {
                alert("@Session["operationMsg"]");
                window.location.href = "/TblBooks/OperationAlert";
            };
    </script>

}

@*<div class="card">
        <table class="table-sm">
            <tr class="bg-success text-light">
                <th>
                    @Html.DisplayNameFor(model => model.BookTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookCategory)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookAuthor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookCopies)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookPub)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookPubName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BookISBN)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Copyright)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    Actions
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookCategory)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookAuthor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookCopies)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookPub)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookPubName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookISBN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Copyright)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAdded)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <div class="btn btn-group-sm">
                            <div class="btn btn-dark btn-sm iconop">
                                <i class="fas fa-edit"></i>
                                @Html.ActionLink("Edit", "Edit", null, new { id = item.BookId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                            <div class="btn btn-sm btn-warning">
                                <i class="fas fa-info-circle iconop"></i>
                                @Html.ActionLink("Details", "Details", null, new { id = item.BookId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                            <div class="btn btn-sm btn-danger">
                                <i class="fas fa-trash iconop"></i>
                                @Html.ActionLink("Delete", "Delete", null, new { id = item.BookId }, new { @class = "", style = "text-decoration:none; color: white" })
                            </div>
                        </div>
                </tr>
            }

        </table>
    </div>*@