MVC Project/LibraryMSMVC/Controllers/AdminTransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryMSMVC.Models;

namespace LibraryMSMVC.Controllers
{

    public class AdminTransactionController : Controller
    {
        private BookEntity bookDb = new BookEntity();
        private TransEntity transDb = new TransEntity();

        // Returns admin request view, here admin can accept and reject the book requests
        public ActionResult Requests()
        {
            return View(transDb.tblTransactions.ToList());
        }
        // Returns all book requests in json format.
        public ActionResult GetAllRequests()
        {
            var transactionList = transDb.tblTransactions.Where(r => r.TranStatus == "Requested").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Accepts the book request.
        public ActionResult AcceptRequest(int? tranId)
        {
           /* try
            {*/
                if (tranId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                tblTransaction transaction = transDb.tblTransactions.FirstOrDefault(t => t.TranId == tranId);
                if (transaction == null)
                {
                    return HttpNotFound();
                }
                transaction.TranStatus = "Accepted";
                transaction.TranDate = DateTime.Now.ToShortDateString();
                transDb.SaveChanges();
                return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/

        }
        // Reject the book request. 
        public ActionResult RejectRequest(int? tranId)
        {
            /*try
            {*/
                if (tranId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                tblTransaction transaction = transDb.tblTransactions.FirstOrDefault(t => t.TranId == tranId);
                if (transaction == null)
                {
                    return HttpNotFound();
                }
                transaction.TranStatus = "Rejected";
                transaction.TranDate = DateTime.Now.ToShortDateString();
                tblBook book = bookDb.tblBooks.FirstOrDefault(b => b.BookId == transaction.BookId);
                book.BookCopies = book.BookCopies + 1;
                bookDb.SaveChanges();
                transDb.SaveChanges();
                return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
        // Returns admin accepted view, here admin can view the accepted books.
        public ActionResult Accepted()
        {
            return View(transDb.tblTransactions.ToList());
        }
        // Returns all accepted books in json format.
        public ActionResult GetAllAccepted()
        {
            var transactionList = transDb.tblTransactions.Where(r => r.TranStatus == "Accepted").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Returns admin return view, here admin can accept book return requests.
        public ActionResult Return()
        {
            return View(transDb.tblTransactions.ToList());
        }
        // Returns all return books in json format.
        public ActionResult GetAllReturn()
        {
            var transactionList = transDb.tblTransactions.Where(r => r.TranStatus == "Returned").ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Accepts the book return request.
        public ActionResult AcceptReturn(int? tranId)
        {

            /*try
            {*/
                if (tranId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                tblTransaction transaction = transDb.tblTransactions.FirstOrDefault(t => t.TranId == tranId);
                if (transaction == null)
                {
                    return HttpNotFound();
                }
                tblBook book = bookDb.tblBooks.FirstOrDefault(b => b.BookId == transaction.BookId);
                book.BookCopies = book.BookCopies + 1;
                bookDb.SaveChanges();
                transDb.tblTransactions.Remove(transaction);
                transDb.SaveChanges();
                return View("Return");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
        // Returns admin home view.
        public ActionResult AdminHome()
        {
            return View();
        }
        // Returns admin about view.
        public ActionResult AdminAbout()
        {
            return View();
        }
        // Returns admin contact view.
        public ActionResult AdminContact()
        {
            return View();
        }
    }
}

MVC Project/LibraryMSMVC/Views/AdminTransaction/Accepted.cshtml
@{
    ViewBag.Title = "Accepted";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h4>Accepted list</h4>
<hr />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Book ISBN
            </th>
            <th>
                Accepted Date
            </th>
            <th>
                User Name
            </th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookISBN
            </th>
            <th>
                TranDate
            </th>
            <th>
                UserName
            </th>
        </tr>
    </tbody>
</table>
<br />


@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        @*Data table plugin*@
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/AdminTransaction/GetAllAccepted",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookISBN" },
                    { "data": "TranDate" },
                    { "data": "UserName" },
                ],
                "language": {
                    "emptyTable": "No data found, Go to Request section to accept a request"
                }
            });
        });
    </script>
}

MVC Project/LibraryMSMVC/Views/AdminTransaction/AdminAbout.cshtml
@{
    ViewBag.Title = "AdminAbout";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>About</h4>
<hr />

<div class="row">
    <div class="col-6">
        <div class="card card-body">
            <h5>Bussiness Information</h5>
            <div>
                <i class="fas fa-flag"></i>
                <span>Opened on 14 Augest 1997</span>
            </div>
            <div>
                <i class="fas fa-brain"></i>
                <span>Mission</span>
                <p>Our vision is to provide modern library management system.</p>
            </div>
        </div>
        <br />
        <div class="card card-body">
            <h5>Meet Our Team</h5>
            <div>
                <i class="fas fa-user-cog"></i>
                <span>Sanoj C R</span>
            </div>
            <div>
                <i class="fas fa-user-cog"></i>
                <span>Sanoj C R</span>
            </div>
            <div>
                <i class="fas fa-user-cog"></i>
                <span>Sanoj C R</span>
            </div>
        </div>

    </div>
    <div class="col">
        <img style="width:100%; height:332px; object-fit: cover;" src="https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
    </div>
</div>
<br />

MVC Project/LibraryMSMVC/Views/AdminTransaction/AdminContact.cshtml
@{
    ViewBag.Title = "AdminContact";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h4>Contact</h4>
<hr />

<div class="row">
    <div class="col-6">
        <div class="card card-body">
            <h5>Address</h5>
            <div>
                <span>Chirakkal Palce,</span>
            </div>
            <div>
                <span>Chemnad,</span>
            </div>
            <div>
                <span>Kasaragod,</span>
            </div>


        </div>
        <br />
        <div class="card card-body">
            <h5>Details</h5>
            <div>
                <i class="fas fa-envelope"></i>
                <span><i>urlms@lms.com</i></span>
            </div>
            <div>
                <i class="fas fa-phone-square"></i>
                <span><i>+91 8281832387</i></span>
            </div>
            <div>
                <i class="fab fa-twitter-square"></i>
                <span><i>@@urlms236</i></span>
            </div>
        </div>

    </div>
    <div class="col">
        <img style="width:100%; height:317px; object-fit: cover;" src="https://images.pexels.com/photos/1333742/pexels-photo-1333742.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" />
    </div>
</div>
<br />

MVC Project/LibraryMSMVC/Views/AdminTransaction/AdminHome.cshtml
@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<div class="row">
    <div class="col">
        <div class="card" style="background-color:#5cb85c">

            <div style="padding-bottom:130px; padding-top:130px;" class="col-5 offset-1 text-light bg-primary">
                <h5 class="card-title">Address</h5>

                <p class="card-text">
                    Chirrakkal Palace,<br>
                    Bengalure, Karnataka,<br>
                    Pin: 676533

                </p>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card bg-dark">
            <div id="carouselExampleCaptions" class="carousel slide" data-interval="2000" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img style="width:100%; height:393px; object-fit: cover;" src="https://images.pexels.com/photos/247899/pexels-photo-247899.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                            <p>
                                "When in doubt, go to the library."
                            </p>
                            <h6 style="text-align: unset; font-style: italic;">Ron Weasley</h6>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img style="width:100%; height:393px; object-fit: cover;" src="https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                            <p>"Nothing is more impotent than an unread library."</p>
                            <h6 style="text-align: unset; font-style: italic;">John Waters</h6>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img style="width:100%; height:393px; object-fit: cover;" src="https://images.pexels.com/photos/2908984/pexels-photo-2908984.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                            <p>"Overall, the library held a hushed exultation, as though the cherished volumes were all singing soundlessly within their covers."</p>
                            <h6 style="text-align: unset; font-style: italic;">Diana Gabaldon</h6>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="jumbotron text-dark bg-light">
    <h1 class="text-center">Welcome to Ur Library Management System!!!!!!</h1>
    <br>
    <p class="lead text-sm-center">
        This is an a online Library management system which helps to you monitor and control the transactons in the library,
        Through this a library user can find the books, request the books, return the books etc...
    </p>
    <hr class="my-2">
    <p>Our vision is to provide modern library management system.</p>
    <a class="btn btn-primary btn-sm text-light " role="button">Learn more</a>
</div>

MVC Project/LibraryMSMVC/Views/AdminTransaction/Requests.cshtml
@model IEnumerable<LibraryMSMVC.Models.tblTransaction>

@{
    ViewBag.Title = "Requests";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Request list</h4>
<hr />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Book ISBN
            </th>
            <th>
                Request Date
            </th>
            <th>
                User Name
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookISBN
            </th>
            <th>
                TranDate
            </th>
            <th>
                UserName
            </th>
        </tr>
    </tbody>
</table>
<br />


@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        @*Data table plugin*@
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/AdminTransaction/GetAllRequests",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookISBN" },
                    { "data": "TranDate" },
                    { "data": "UserName" },
                    {
                        "data": "TranId", "render": function (idhere) {

                            return " <a onclick='acceptRequest()' class='btn btn-sm btn-primary text-light' data-toggle='tooltip' title='Accept book request' href='@Url.Action("AcceptRequest", "AdminTransaction")?tranId=" + idhere + "'> <i class='fas fa-check-circle'></i> Accept</a> <a onclick='rejectRequest()' class='btn btn-sm btn-danger text-light' data-toggle='tooltip' title='Reject book request' style='margin-left:px' href='@Url.Action("RejectRequest", "AdminTransaction")?tranId=" + idhere + "'> <i class='fas fa-times-circle'></i></i> Reject</a>";
                        },
                        "orderable": false,
                        "width": "160px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Wait for the users to take action."
                }
            });
        });

        @*Scripts for request alert*@
        function acceptRequest(){
                alert("Book request accepted successfully")
        };

        @*Scripts for reject alert*@
        function rejectRequest(){
                alert("Book request rejected successfully")
        };
    </script>
}

MVC Project/LibraryMSMVC/Views/AdminTransaction/Return.cshtml
@model IEnumerable<LibraryMSMVC.Models.tblTransaction>

@{
    ViewBag.Title = "Return";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h4>Return list</h4>
<hr />

@*External stylesheet for data table plugins*@
<link rel="stylesheet" , href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" />
<link rel="stylesheet" , href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" />
<table width="100%" class="table table-hover table-bordered" id="example">
    <thead class="bg-success text-light">
        <tr>
            <th>
                Book Title
            </th>
            <th>
                Book ISBN
            </th>
            <th>
                Return Date
            </th>
            <th>
                User Name
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                BookTitle
            </th>
            <th>
                BookISBN
            </th>
            <th>
                TranDate
            </th>
            <th>
                UserName
            </th>
        </tr>
    </tbody>
</table>
<br />

@*Java scripts*@
@section scripts{
    @*External scripts for data table plugins*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        @*Data table plugin*@
        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "/AdminTransaction/GetAllReturn",
                    "type": "get",
                    "datatype": "json",
                },
                "columns": [
                    { "data": "BookTitle" },
                    { "data": "BookISBN" },
                    { "data": "TranDate" },
                    { "data": "UserName" },
                    {
                        "data": "TranId", "render": function (idhere) {

                            return " <a onclick='acceptReturn()' class='btn btn-sm btn-primary text-light' data-toggle='tooltip' title='Accept return request' href='@Url.Action("AcceptReturn", "AdminTransaction")?tranId=" + idhere + "'> <i class='fas fa-check-circle'></i> Accept</a> ";
                        },
                        "orderable": false,
                        "width": "60px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, Wait for the users to take action."
                }
            });
        });
        @*Scripts for accept alert*@
        function acceptReturn(){
                alert("Return request accepted successfully")
        };
    </script>
}